services:
  dbx:
    image: t8y2/dbx:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:4224"
    environment:
      - DBX_PASSWORD=${PANEL_DB_PASSWORD}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
